Add ssh port configuration
Non default ssh port can be setted
in .deliver/config as SSH_PORT

diff --git a/libexec/core b/libexec/core
--- a/libexec/core
+++ b/libexec/core
@@ -300,10 +300,10 @@ __remote() {
 
   for _host in $_hosts
   do
-    ssh -o ConnectTimeout="$SSH_TIMEOUT" "$_host" "$_remote_job $SILENCE" &
+    ssh -p $SSH_PORT -o ConnectTimeout="$SSH_TIMEOUT" "$_host" "$_remote_job $SILENCE" &
     background_jobs_pids+=("$!")
-    local _background_job="ssh -o ConnectTimeout=$SSH_TIMEOUT $_host $_remote_job $SILENCE"
-    background_jobs+=("ssh -o ConnectTimeout=$SSH_TIMEOUT $_host $_error_info_for_remote_job $SILENCE")
+    local _background_job="ssh -p $SSH_PORT -o ConnectTimeout=$SSH_TIMEOUT $_host $_remote_job $SILENCE"
+    background_jobs+=("ssh -p $SSH_PORT -o ConnectTimeout=$SSH_TIMEOUT $_host $_error_info_for_remote_job $SILENCE")
     background_jobs_hosts+=("$_host")
   done
 
@@ -320,7 +320,7 @@ __sync_remote() {
   [[ $(wc -w <<< "$_hosts") -gt 1 ]] && error "Sync commands can be executed on one host only, but serveral hosts are configured ($_hosts)."
   local _host="$_hosts"
   if [[ "$VERBOSE" = "true" ]]; then
-    ssh -t -A -q -o ConnectTimeout="$SSH_TIMEOUT" "$_host" "$_remote_job" || error "\nA remote command failed on:
+    ssh -p $SSH_PORT -t -A -q -o ConnectTimeout="$SSH_TIMEOUT" "$_host" "$_remote_job" || error "\nA remote command failed on:
 
   $_host
 
@@ -330,7 +330,7 @@ on that host is printed below for debugging purposes:
 FAILED with exit status $?:\n${_remote_job}\n"
   else
     local _output _status
-    _output=$(ssh -A -o ConnectTimeout="$SSH_TIMEOUT" "$_host" "$_remote_job" 2>&1)
+    _output=$(ssh -p $SSH_PORT -A -o ConnectTimeout="$SSH_TIMEOUT" "$_host" "$_remote_job" 2>&1)
     _status=$?
     [[ "$_status" -ne 0 ]] && echo "$_output" && error "\nA remote command failed on:
 
